spring.application.name=gestion-juridica-backend

# Configuración para desarrollo local
spring.datasource.url=jdbc:mysql://localhost:3306/despacho_juridico_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=1234

# Esto hará que Hibernate cree las tablas por ti
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.open-in-view=false

spring.jackson.serialization.fail-on-empty-beans=false